= Cake.GitLab

:link-cake: link:https://cakebuild.net[Cake]
:link-cakefrosting: link:https://cakebuild.net/docs/running-builds/runners/cake-frosting[Cake Frosting]
:link-ngitlab: link:https://github.com/ubisoft/NGitLab[NGitLab]

:url-build-statusbadge: https://github.com/ap0llo/Cake.GitLab/actions/workflows/build.yml/badge.svg
:url-build-latest: https://github.com/ap0llo/Cake.GitLab/actions/workflows/build.yml

:url-nuget-badge: https://img.shields.io/nuget/v/Cake.GitLab.svg
:url-nuget-package: https://www.nuget.org/packages/Cake.GitLab

Cake.GitLab is a {link-cake} Addin that provides aliases for interaction with the link:https://docs.gitlab.com/ee/api/rest/[GitLab API].

It is based on {link-ngitlab}.

image:{url-build-statusbadge}[link={url-build-latest}]

image:{url-nuget-badge}[link={url-nuget-package}]

== Usage

=== Install the Addin

Install the addin into your Cake build.

* If you are using Cake scripting, use the `#addin` preprocessor directive:
+
[source,cs]
----
#addin nuget:?package=Cake.GitLab&version=VERSION
----
* If you are using {link-cakefrosting}, install the addin by adding a package reference to your project:
+
[source,xml]
----
<PackageReference Include="Cake.GitLab" Version="VERSION" /> 
----

==== Use prerelease version

* Releases of Cake.GitLab are available on  link:https://nuget.org/packages/Cake.GitLab[nuget.org]
* Prerelease versions are available in the CI feed on [feedz.io](https://feedz.io/org/ap0llo/repository/cake-gitlab-ci)
  To use prerelease packages, add the feed `https://f.feedz.io/ap0llo/cake-gitlab-ci/nuget/index.json` to your `nuget.config`, e.g.
+
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="cake-gitlab-ci" value="https://f.feedz.io/ap0llo/cake-gitlab-ci/nuget/index.json" />
  </packageSources>
</configuration>
----

=== Available Aliases

For a list of aliases provided by the addin, please refer to the link:./docs/README.md[documentation].

== License

Cake.GitLab is licensed under the MIT License.

For details see link:https://github.com/ap0llo/Cake.GitLab/blob/main/LICENSE[]


== Building from source

Building the project from source requires the .NET SDK (version as specified in link:global.json[]) and uses Cake.

To execute the default build, run

[source,ps1]
----
.\build.ps1
----

This will build the project, run all tests and pack the NuGet package.


== Versioning and Branching

The version of the addin is automatically derived from git and the information in `version.json` using link:https://github.com/AArnott/Nerdbank.GitVersioning[Nerdbank.GitVersioning]:

* The `main` branch always contains the latest version. Packages produced from `main` are always marked as pre-release versions (using the -pre suffix).
* Stable versions are built from release branches. Build from release branches will have no -pre suffix
* Builds from any other branch will have both the -pre prerelease tag and the git commit hash included in the version string

To create a new release branch use the link:https://www.nuget.org/packages/nbgv/[nbgv tool]:

[source,sh]
----
dotnet tool install --global nbgv
nbgv prepare-release
----
