name: Cake.GitLab CI

# Trigger build for pushes to the main branch and all release branches
# As well as all Pull Requests targeting these branches
on:
  push:
    branches: 
      - $default-branch 
      - release/*
  pull_request:
    branches: 
      - $default-branch
      - release/*
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run Build
        run: |-
          echo "Hello World"

